
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
from tkinter import messagebox
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\8000007035\Desktop\b\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def logar(): #incluir

    print('clicked')

    usuario = entry_1.get() #usuário
    senha = entry_1.get()
    
    if senha == oi and usuario marcos:


     print('teste')

    else:

      messagebox.showwarning('Erro verifique a senha e o nome')



 

#Para ocultar a senha, utilize o seguinte comando

entry_1.config(show="*")
window = Tk()

window.geometry("360x800")
window.configure(bg = "#6734F8")

canvas = Canvas(
    window,
    bg = "#6734F8",
    height = 800,
    width = 360,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    42.0,
    558.0,
    318.0,
    601.0,
    fill="#F58C1D",
    outline="")


image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    180.0,
    216.0,
    image=image_image_1
)

canvas.create_rectangle(
    42.0,
    372.0,
    318.0,
    415.0,
    fill="#FFFFFF",
    outline="")
canvas.create_rectangle(
    42.0,
    465.0,
    318.0,
    508.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
